### ISSUE TITLE
ArgumentError (Missing :cas_base_url parameter!)

### ISSUE THREAD

**Issue by Cheomm88** [ninech/redmine_cas#25]
Hi,
I'm getting this error after installing redmine (3.3.4) and redmine_cas plugin.

ArgumentError (Missing :cas_base_url parameter!):
  plugins/redmine_cas/lib/redmine_cas.rb:21:in `setup!'
  plugins/redmine_cas/init.rb:26:in `block (2 levels) in <top (required)>'  

The code:

def setup!
    return unless enabled?
    CASClient::Frameworks::Rails::Filter.configure(
      :cas_base_url => setting(:cas_url),
      :logger => Rails.logger,
      :enable_single_sign_out => single_sign_out_enabled?
    )
  end

Any idea what's wrong??

**Comment by born4new** [comment]
Hey @Cheomm88,

Could you double-check that the plugin is correctly configured in Redmine? (steps 3 and 4 of the [install](https://github.com/ninech/redmine_cas#installation) part)

**Comment by Cheomm88** [comment]
Hi,
I'm not able to enter on the config as the Redmine returns a 500 error.
Checking the logs I found the information that I sent in my first post.



2017-11-21 6:09 GMT+00:00 David Dieulivol <notifications@github.com>:

**Comment by born4new** [comment]
Okay: I need some clarifications on your side here.

Are you receiving a 500 from Redmine when trying to do the step 3 of the [install],
 or when doing the step 4(https://github.com/ninech/redmine_cas#installation)?

Any other things that could help us debug would be greatly appreciated as well (screenshots, logs, current configuration ...)

**Comment by Cheomm88** [comment]
Hi,
I just copied the plugin and restarted the server. After that I wasn't able to enter into the Redmine. So I couldn't do the steps 3/4 as I'm not able to load Redmine.

The plugin is a redmine_root/plugins/redmine_cas/
(Inside the redmine_cas is all the stuff)

I just checked again the logs after trying to enter on the website.

> F, [2017-11-21T08:30:59.076236 #21535] FATAL -- : 
> ArgumentError (Missing :cas_base_url parameter!):
>   plugins/redmine_cas/lib/redmine_cas.rb:21:in `setup!'
>   plugins/redmine_cas/init.rb:26:in `block (2 levels) in <top (required)>'


![image](https://user-images.githubusercontent.com/18485978/33062029-c9a66672-ce95-11e7-8fc9-a99743de576b.png)


Is supported the Redmine 3.3.4 ?

**Comment by born4new** [comment]
We use that plugin (version 1.2.1) with Redmine `3.3.3` currently, so it should work in your case as well.

Could you try a fresh install again maybe? That would look like this:

1. Dropping the `redmine_cas` folder in the redmine plugins folder.
2. Restarting your Redmine and ensuring that it works fine again
3. Cloning the repository again in the Redmine plugins folder
4. Restarting your Redmine instance
5. See if you can see the plugin in the plugins list.

If that doesn't work for you, I'll try to reproduce the bug locally with Redmine 3.3.4.

**Comment by Cheomm88** [comment]
I've removed the redmine_cas folder in redmine plugins and restarted my Redmine server.

It was working fine. Then I cloned the git repository:

> cd /usr/local/redmine/plugins/
> git clone https://github.com/ninech/redmine_cas.git

 After this I restarted my Redmine server, then again I got the error 500 and in the production log.

> ArgumentError (Missing :cas_base_url parameter!):
>   plugins/redmine_cas/lib/redmine_cas.rb:21:in `setup!'
>   plugins/redmine_cas/init.rb:28:in `block (2 levels) in <top (required)>'

**Comment by Cheomm88** [comment]
Finally I fixed this.

Seems that there was an old installation of the plugin in the database but not in the plugins folder. The data was still there but wasn't the expected and that was generating the issue.

Data stored previously:

>  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
> enabled: 'false'
> cas_base_url: https://mycas.com
> cas_logout: 'true'

I updated the data from database in the table settings, the row with name = plugin_redmine_cas to

> --- !ruby/hash-with-ivars:ActionController::Parameters
> elements:
>   enabled: '1'
>   cas_url: https:/mycas.com/
>   attributes_mapping: ''
> ivars:
>   :@permitted: false

**Comment by born4new** [comment]
Good to know, thanks for the headsup!
