### ISSUE TITLE
Don't know why the user couldn't be created

### ISSUE THREAD

**Issue by anthony-o** [ninech/redmine_cas#5]
I've got ""`myuser`" was authenticated but could not be created automatically in Redmine. It must be added manually." message and the problem is I don't know why the user creation cannot be done.
In the setup I've set those attributes mapping : id=uniqueId&login=uniqueId&firstname=firstName&lastname=lastName&mail=email (because my CAS server sends "uniqueId", "firstName", "lastName" and "email" attributes).

For example, my CAS server doesn't send the hashed password, is this a problem ?

**Comment by andyshi2008** [comment]
where is the log ?

**Comment by pencil** [comment]
Usually `/path/to/redmine/log/production.log`
